### ISSUE TITLE
Take over original project

### ISSUE THREAD

**Issue by TheDauntless** [jseigelis/patch-apk#1]
The original project has now been archived (the one where I forked from), so maybe it's a good idea to update the readme.md to explain the situation? Your fork seems to be the more active one and you've done quite some updates, so I'll be using your fork in the future :).

**Comment by jseigelis** [comment]
i see you merged my changes over + someone else made further improvements, so im going to sync this fork with yours and we can go from there. if you also archive eventually, this will presumably become de facto standard repo for this script

**Comment by jseigelis** [comment]
https://github.com/jseigelis/patch-apk/pull/2
